import * as pdfjsLib from 'https://cdnjs.cloudflare.com/ajax/libs/pdf.js/4.10.38/pdf.min.mjs';
pdfjsLib.GlobalWorkerOptions.workerSrc='https://cdnjs.cloudflare.com/ajax/libs/pdf.js/4.10.38/pdf.worker.min.mjs';
const $=s=>document.querySelector(s);let rows=[];
const money=n=>(Number(n)||0).toLocaleString('es-ES',{minimumFractionDigits:2,maximumFractionDigits:2});
const num=s=>{if(!s)return 0;let x=String(s).replace(/\s/g,'').replace(/\./g,'').replace(',','.').replace(/[^0-9.-]/g,'');return Number(x)||0};
const euroValues=s=>[...String(s||'').matchAll(/(-?[\d.]+,\d{2})\s*€/g)].map(m=>num(m[1]));
const lastEuro=s=>{const v=euroValues(s);return v.length?v[v.length-1]:0};const round2=n=>Math.round((n+Number.EPSILON)*100)/100;
function makeLines(items){const pts=items.filter(i=>i.str&&i.str.trim()).map(i=>({s:i.str.trim(),x:i.transform[4],y:i.transform[5]}));pts.sort((a,b)=>b.y-a.y||a.x-b.x);const groups=[];for(const p of pts){let g=groups.find(x=>Math.abs(x.y-p.y)<=2.2);if(!g){g={y:p.y,items:[]};groups.push(g)}g.items.push(p)}groups.sort((a,b)=>b.y-a.y);return groups.map(g=>g.items.sort((a,b)=>a.x-b.x).map(x=>x.s).join(' ').replace(/\s+/g,' ').trim())}
async function pdfData(file){const data=new Uint8Array(await file.arrayBuffer());const pdf=await pdfjsLib.getDocument({data}).promise;const pages=[];for(let i=1;i<=pdf.numPages;i++){const page=await pdf.getPage(i),c=await page.getTextContent();pages.push(makeLines(c.items))}return {pages,text:pages.flat().join('\n')}}
const findLine=(lines,re)=>lines.find(l=>re.test(l))||'';function section(lines,startRe,endRes){const a=lines.findIndex(l=>startRe.test(l));if(a<0)return [];let b=lines.length;for(let i=a+1;i<lines.length;i++){if(endRes.some(r=>r.test(lines[i]))){b=i;break}}return lines.slice(a,b)}function rowFor(lines,p){return lines.find(l=>new RegExp(`^\\s*P${p}:?\\b`,'i').test(l))||''}function sumPeriodTotals(lines){let total=0;for(let p=1;p<=6;p++){const line=rowFor(lines,p);if(line)total+=lastEuro(line)}return round2(total)}
function parseFenie(data,file){const lines=data.pages[0]||[],text=data.text,companyLine=findLine(lines,/Raz[oó]n Social:/i),company=(companyLine.match(/Raz[oó]n Social:\s*(.+)$/i)||[])[1]?.trim()||'',cups=((findLine(lines,/CUPS:/i).match(/ES[A-Z0-9]{16,24}/i)||text.match(/ES[A-Z0-9]{16,24}/i)||[])[0])||'',tariff=((findLine(lines,/Tarifa:/i).match(/(2\.0TD|3\.0TD|6\.1TD|6\.2TD|6\.3TD|6\.4TD)/i)||text.match(/(2\.0TD|3\.0TD|6\.1TD|6\.2TD|6\.3TD|6\.4TD)/i)||[])[1])||'—',period=((findLine(lines,/Periodo Facturaci[oó]n:/i).match(/\d{2}\/\d{2}\/\d{4}\s*-\s*\d{2}\/\d{2}\/\d{4}\s*\(\d+\s*d[ií]as\)/i)||[])[0])||'Por identificar',total=lastEuro(findLine(lines,/TOTAL FACTURA/i));
const energySec=section(lines,/T[eé]rmino (?:de )?energ[ií]a(?: variable)?/i,[/T[eé]rmino de potencia/i]),periods={};let kwh=0;for(let p=1;p<=6;p++){const line=rowFor(energySec,p);if(!line)continue;const km=line.match(/([\d.]+,\d{2})\s*kWh/i),consumption=km?num(km[1]):0,euros=euroValues(line),cost=euros.length?(euros.length>1?euros[euros.length-2]:euros[0]):0,prices=[...line.matchAll(/([\d.,]+)\s*€\/kWh/gi)].map(m=>num(m[1])),price=prices.length?prices[prices.length-1]:0;periods[`P${p}`]={consumption,cost,price};kwh+=consumption}const energy=round2(Object.values(periods).reduce((s,x)=>s+(x.cost||0),0));
const powerSec=section(lines,/T[eé]rmino de potencia/i,[/Excesos? de Potencia/i,/Energ[ií]a reactiva/i,/Bono social/i]),contracted={};for(let p=1;p<=6;p++){const line=rowFor(powerSec,p),m=line.match(/([\d.]+,\d{3})\s*kW/i);if(m)contracted[`P${p}`]=num(m[1])}const power=sumPeriodTotals(powerSec),excess=sumPeriodTotals(section(lines,/Excesos? de Potencia/i,[/Energ[ií]a reactiva/i,/Bono social/i,/Impuesto electricidad/i])),reactive=sumPeriodTotals(section(lines,/Energ[ií]a reactiva/i,[/Compensaci[oó]n Excedente/i,/Bono social/i,/Impuesto electricidad/i]));
const compensationLine=findLine(lines,/Compensaci[oó]n Excedente/i);let compensation=lastEuro(compensationLine);if(compensation>0)compensation=-compensation;if(!compensation){const cm=text.match(/Compensaci[oó]n Excedente[^\n]*?(-?[\d.]+,\d{2})\s*€/i);if(cm)compensation=num(cm[1])>0?-num(cm[1]):num(cm[1])}const social=lastEuro(findLine(lines,/Bono social/i)),tax=lastEuro(findLine(lines,/Impuesto electricidad/i)),rental=lastEuro(findLine(lines,/Alquiler Equipo medida/i)),vat=lastEuro(findLine(lines,/^IVA\b/i)),accounted=round2(energy+power+excess+reactive+compensation+social+tax+rental+vat),diff=round2(total-accounted),balanced=total>0&&Math.abs(diff)<=0.05;
const missing=[];if(!company)missing.push('empresa');if(!cups)missing.push('CUPS');if(period==='Por identificar')missing.push('periodo');if(!total)missing.push('total');if(!kwh)missing.push('consumo');if(!energy)missing.push('energía');if(!power)missing.push('potencia');const readOk=balanced&&!missing.length;let opportunity='Sin alertas';if(excess>0)opportunity=`Exceso de potencia: ${money(excess)} €`;else if(reactive>0)opportunity=`Reactiva: ${money(reactive)} €`;else{const c=Object.values(contracted);if(c.length&&Math.max(...c)>=50)opportunity=`Potencia contratada elevada (${money(Math.max(...c))} kW): revisar maxímetros e histórico`}let readMessage='Lectura correcta';if(missing.length)readMessage=`Falta ${missing.join(', ')}`;else if(!balanced)readMessage=`Descuadre: ${money(diff)} €`;return {file:file.name,company:company||'Por identificar',cups,period,tariff,kwh,energy,power,excess,reactive,compensation,social,rental,tax,vat,total,accounted,diff,balanced,readOk,readMessage,avg:kwh?total/kwh:0,opportunity,periods,contracted}}
async function process(files){for(const file of files){if(!file.name.toLowerCase().endsWith('.pdf'))continue;try{rows.push(parseFenie(await pdfData(file),file))}catch(e){rows.push({file:file.name,company:'Error de lectura',cups:'',period:'',tariff:'—',kwh:0,energy:0,power:0,excess:0,reactive:0,compensation:0,social:0,rental:0,tax:0,vat:0,total:0,accounted:0,diff:0,balanced:false,readOk:false,readMessage:e.message,avg:0,opportunity:'—',periods:{},contracted:{}})}render()}}
function render(){const body=$('#resultsBody');body.innerHTML=rows.length?'':`<tr class="empty"><td colspan="16">Aún no hay facturas procesadas.</td></tr>`;for(const r of rows){const tr=document.createElement('tr'),balance=r.total?(r.balanced?'OK':`${money(r.diff)} €`):'—';tr.innerHTML=`<td><span class="status ${r.readOk?'ok':'danger'}">${r.readOk?'Correcta':'Error'}</span></td><td>${r.company}</td><td>${r.cups||'—'}</td><td>${r.period}</td><td>${r.tariff}</td><td>${money(r.kwh)}</td><td>${money(r.energy)}</td><td>${money(r.power)}</td><td>${money(r.excess)}</td><td>${money(r.reactive)}</td><td>${money(r.social+r.rental+r.compensation)}</td><td>${money(r.tax+r.vat)}</td><td><strong>${money(r.total)}</strong></td><td><strong>${balance}</strong></td><td>${r.avg?money(r.avg):'—'}</td><td class="opp">${r.opportunity}</td>`;body.appendChild(tr)}$('#statInvoices').textContent=rows.length;$('#statOk').textContent=rows.filter(x=>x.readOk).length;$('#statReview').textContent=rows.filter(x=>!x.readOk).length;$('#statKwh').textContent=money(rows.reduce((s,x)=>s+x.kwh,0))+' kWh';$('#statTotal').textContent=money(rows.reduce((s,x)=>s+x.total,0))+' €';$('#exportExcel').disabled=!rows.length}
const XL={navy:'10233F',blue:'1834B8',green:'27943B',lightBlue:'EEF1FF',lightGreen:'E7F5E9',orange:'F4B740',lightOrange:'FFF2D7',red:'B42318',lightRed:'FDE9E7',gray:'65758A',light:'F4F7FB',white:'FFFFFF',line:'DCE4ED'};
const titleStyle={font:{bold:true,color:{rgb:XL.white},sz:18},fill:{fgColor:{rgb:XL.navy}},alignment:{vertical:'center'}};const headerStyle={font:{bold:true,color:{rgb:XL.white},sz:10},fill:{fgColor:{rgb:XL.blue}},alignment:{vertical:'center',wrapText:true},border:{bottom:{style:'thin',color:{rgb:XL.navy}}}};
function styleSheet(ws,widths,freeze='A4'){ws['!cols']=widths.map(w=>({wch:w}));ws['!autofilter']={ref:ws['!ref']};ws['!freeze']={xSplit:0,ySplit:3,topLeftCell:freeze,activePane:'bottomLeft',state:'frozen'};ws['!views']=[{showGridLines:false}]}
function cell(ws,a){return ws[a]||(ws[a]={t:'s',v:''})}function setStyle(ws,a,s){cell(ws,a).s=s}function mergeTitle(ws,last,title,subtitle){ws['!merges']=ws['!merges']||[];ws['!merges'].push({s:{r:0,c:0},e:{r:0,c:last}},{s:{r:1,c:0},e:{r:1,c:last}});cell(ws,'A1').v=title;cell(ws,'A2').v=subtitle;setStyle(ws,'A1',titleStyle);setStyle(ws,'A2',{font:{color:{rgb:XL.gray},italic:true,sz:10},fill:{fgColor:{rgb:XL.light}},alignment:{vertical:'center'}});ws['!rows']=[{hpt:28},{hpt:20},{hpt:26}]}
function styleTable(ws,headers,startRow=3){headers.forEach((_,i)=>setStyle(ws,XLSX.utils.encode_cell({r:startRow-1,c:i}),headerStyle));const range=XLSX.utils.decode_range(ws['!ref']);for(let r=startRow;r<=range.e.r;r++){for(let c=0;c<=range.e.c;c++){const a=XLSX.utils.encode_cell({r,c}),x=ws[a];if(!x)continue;x.s={font:{color:{rgb:'1F2937'},sz:9},alignment:{vertical:'center',wrapText:c===range.e.c},fill:{fgColor:{rgb:r%2?XL.white:'F8FAFC'}}};}}}
function exportExcel(){
 const summaryHeaders=['Estado','Empresa','CUPS','Periodo','Tarifa','Consumo kWh','Energía €','Potencia €','Excesos €','Reactiva €','Comp. excedentes €','Otros €','Impuestos €','Total factura €','Cuadre','Coste €/kWh','Oportunidad energética'];
 const summaryRows=rows.map(r=>[r.readOk?'CORRECTA':'ERROR',r.company,r.cups,r.period,r.tariff,r.kwh,r.energy,r.power,r.excess,r.reactive,r.compensation,r.social+r.rental,r.tax+r.vat,r.total,r.balanced?'OK':'REVISAR',r.avg,r.opportunity]);
 const ws=XLSX.utils.aoa_to_sheet([['INSTAL·LACIONS BT · INFORME ENERGÉTICO'],['Resumen de facturas procesadas · Alpha'],summaryHeaders,...summaryRows]);mergeTitle(ws,16,'INSTAL·LACIONS BT · INFORME ENERGÉTICO','Resumen de facturas procesadas · generado desde Energy Advisor Alpha');styleTable(ws,summaryHeaders);styleSheet(ws,[12,28,27,27,10,14,13,13,12,12,16,12,13,15,11,14,38]);
 for(let i=4;i<=rows.length+3;i++){['F','G','H','I','J','K','L','M','N','P'].forEach(col=>{if(ws[`${col}${i}`])ws[`${col}${i}`].z=col==='F'?'#,##0.00 "kWh"':'#,##0.00;[Red](#,##0.00);-'});if(ws[`P${i}`])ws[`P${i}`].z='0.0000';const ok=ws[`A${i}`];if(ok)ok.s={font:{bold:true,color:{rgb:rows[i-4].readOk?'19742B':XL.red}},fill:{fgColor:{rgb:rows[i-4].readOk?XL.lightGreen:XL.lightRed}},alignment:{horizontal:'center'}};const opp=ws[`Q${i}`];if(opp&&rows[i-4].opportunity!=='Sin alertas')opp.s={font:{bold:true,color:{rgb:'8B5600'}},fill:{fgColor:{rgb:XL.lightOrange}},alignment:{wrapText:true}}}
 const detailHeaders=['Empresa','CUPS','Periodo','Tarifa'];for(let p=1;p<=6;p++)detailHeaders.push(`P${p} kWh`,`P${p} coste €`,`P${p} €/kWh`,`P${p} potencia kW`);const detailRows=rows.map(r=>{const a=[r.company,r.cups,r.period,r.tariff];for(let p=1;p<=6;p++){const x=r.periods[`P${p}`]||{};a.push(x.consumption||0,x.cost||0,x.price||0,r.contracted[`P${p}`]||0)}return a});const wd=XLSX.utils.aoa_to_sheet([['INSTAL·LACIONS BT · DETALLE POR PERIODOS'],['Consumo, coste de energía, precio y potencia contratada P1–P6'],detailHeaders,...detailRows]);mergeTitle(wd,detailHeaders.length-1,'INSTAL·LACIONS BT · DETALLE POR PERIODOS','Consumo, coste de energía, precio y potencia contratada por periodo P1–P6');styleTable(wd,detailHeaders);styleSheet(wd,[28,27,27,10,...Array(6).fill([12,13,13,14]).flat()]);
 const oppRows=rows.filter(r=>r.opportunity!=='Sin alertas').map(r=>[r.company,r.cups,r.period,r.tariff,r.kwh,r.total,r.excess,r.reactive,Math.max(0,...Object.values(r.contracted)),r.opportunity]);const oh=['Empresa','CUPS','Periodo','Tarifa','Consumo kWh','Total €','Excesos €','Reactiva €','Potencia máx. contratada kW','Oportunidad / siguiente revisión'];const wo=XLSX.utils.aoa_to_sheet([['INSTAL·LACIONS BT · OPORTUNIDADES DE AHORRO'],['Puntos detectados automáticamente para revisión energética'],oh,...oppRows]);mergeTitle(wo,9,'INSTAL·LACIONS BT · OPORTUNIDADES DE AHORRO','Puntos detectados automáticamente. Validar con histórico antes de recomendar cambios de potencia.');styleTable(wo,oh);styleSheet(wo,[28,27,27,10,14,14,13,13,22,48]);
 const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,ws,'Resumen');XLSX.utils.book_append_sheet(wb,wd,'Detalle P1-P6');XLSX.utils.book_append_sheet(wb,wo,'Oportunidades');wb.Props={Title:'Informe energético',Subject:'Análisis de facturas eléctricas',Author:'Instal·lacions BT',Company:'Instal·lacions BT'};XLSX.writeFile(wb,'Informe_Energetico_Instalacions_BT.xlsx')}
const dz=$('#dropZone'),input=$('#fileInput');$('#pickFiles').onclick=()=>input.click();input.onchange=e=>process([...e.target.files]);['dragenter','dragover'].forEach(x=>dz.addEventListener(x,e=>{e.preventDefault();dz.classList.add('drag')}));['dragleave','drop'].forEach(x=>dz.addEventListener(x,e=>{e.preventDefault();dz.classList.remove('drag')}));dz.addEventListener('drop',e=>process([...e.dataTransfer.files]));$('#exportExcel').onclick=exportExcel;$('#clearData').onclick=()=>{rows=[];render()};